/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BGuildCard: typeof import('./components/guild/BGuildCard.vue')['default']
    BGuildIcon: typeof import('./components/guild/BGuildIcon.vue')['default']
    BMemberAvatarIcon: typeof import('./components/member/BMemberAvatarIcon.vue')['default']
    BNavigationDrawer: typeof import('./components/layout/BNavigationDrawer.vue')['default']
    BScrollText: typeof import('./components/global/text/BScrollText.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnackbarProvider: typeof import('./components/provider/SnackbarProvider.vue')['default']
  }
}
